name: CI

on:
    push:
        branches:
            - main
        paths-ignore:
            - "README.md"
            - "helm/**"

jobs:

    build:
        runs-on: ubuntu-latest
        
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up go 1.22
              uses: actions/setup-go@v2
              with:
                go-version: 1.22
            - name: Build
              run: go build -o go-web-app

            - name: Test
              run: go test ./...

    code-quality:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Run golangci-lint
              uses: golangci/golangci-lint-action@v6
              with:
                version: v1.56.2

    push:
        runs-on: ubuntu-latest

        needs: build

        steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v4
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ap-south-1

        - name: Login to Amazon ECR
          id: login-ecr
          uses: aws-actions/amazon-ecr-login@v2
          with:
            mask-password: 'false'

        - name: Build and Push to AWS ECR
          run: | 
            docker build -t public.ecr.aws/p3b6w3x9/eks-cluster:${{github.run_id}} .
            aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/p3b6w3x9
            docker push public.ecr.aws/p3b6w3x9/eks-cluster:${{github.run_id}}


    update-newtag-in-helm-chart:   
        runs-on: ubuntu-latest

        needs: push

        steps:
        - name: Checkout repository
          uses: actions/checkout@v4
          with:
            token: ${{ secrets.TOKEN }}

        - name: Update tag in Helm chart
          run: |
            sed -i 's/tag: .*/tag: "${{github.run_id}}"/' helm/go-web-app-chart/values.yaml

        - name: Commit and push changes
          run: |
            git config --global user.email "tanmoycoc44@gmail.com"
            git config --global user.name "Tanmoy009"
            git add helm/go-web-app-chart/values.yaml
            git commit -m "Update tag in Helm chart"
            git push
